### ISSUE TITLE
The 3D mode of the  Iflight succex-e f7  is not available

### ISSUE THREAD

**Issue by clsfpv** [emuflight/EmuConfigurator#523] opened 2024-05-03 08:12 UTC
#In 3D mode, the logic of the motor is reversed, and when I reverse it, the plane goes into a death roll, similar to the propeller or motor rotation in the wrong direction.

#Step 1: Activate the 3D mode.
  Step 2: Activate ARM.
  Step 3: Climb the aircraft to a certain height.
  Step 4: Turn the plane upside down and lower the throttle to the reverse state.
  Step 5: Bugs appear.

#I hope the 3D mode will work properly.

#target: IFLIGHT_SUCCEX_E_F7(emuflight0.4.0)

#Windows10

Thank you for reading!

**Comment by nerdCopter** [comment] 2024-05-03 12:47
duplicate of https://github.com/emuflight/EmuFlight/issues/873

**Closed** 2024-07-12 13:24 UTC
