### ISSUE TITLE
Mac OS damaged file error

### ISSUE THREAD

**Issue by flyandride** [emuflight/EmuConfigurator#17] opened 2019-10-05 19:54 UTC
I've tried downloading the Mac version several times.  I've gotten a very slow download that stalled and when it did finish I got a damaged file error.  

Downloading the Windows version also stalls.

**Comment by besser** [comment] 2019-10-06 20:36
That's a same issue that occour with betaflight configurator. If you clone this repo and compile your self the configurator run with no problem.

[https://imgur.com/a/VA8QQrt](url)

**Comment by loutwice** [comment] 2019-10-06 21:28
github sometime can mess with the download i will advise you to use a download manager as jdownloader for example   . let me know @flyandride

**Comment by soulinux** [comment] 2019-10-09 00:26
Which version works on Mojave 10.14.6?

**Comment by loutwice** [comment] 2019-10-09 02:25
0.2.0 should work - what is your error @soulinux ?

**Comment by soulinux** [comment] 2019-10-12 00:13
Thanks @loutwice,  problem solved with jdownloader

**Comment by gretel** [comment] 2019-10-13 18:03
for now i have hard time see any actual connection using a third party downloader.
am very suspicious on that being **not** a local issue, like stream-changing firewalls, antivirii, or alike.
personally, i can reproduce this issue both ways, not using anything like third party http client.

**Comment by SupraDolph** [comment] 2019-10-19 12:32
jdownloader also works for me. Thanks.

**Comment by gretel** [comment] 2019-10-19 15:29
we need to know what `jdownloader` changes. it's a file transferred via `http` there can't be no magic :)

**Comment by SupraDolph** [comment] 2019-10-19 15:52
I have no idea why that happen. It's the first time I encountered this kind of issue. I have also tried with the new version of Betaflight configurator. The same issue was happened.

**Comment by gretel** [comment] 2019-10-19 16:01
@SupraDolph we are working on providing signed apps for `osx` as soon as possible.

**Comment by loutwice** [comment] 2020-01-01 22:19
i think this one is solved by now? let me now

**Closed** 2020-03-12 01:12 UTC
Labels: bug
