### ISSUE TITLE
MacOSX 10.14.6 Mojave 

### ISSUE THREAD

**Issue by soulinux** [emuflight/EmuConfigurator#16] opened 2019-10-05 17:44 UTC
None of the available versions work with Mojave.
Is there any configuration required for perfect operation? I tried to install on Mojave version 10.14.6

**Comment by gretel** [comment] 2019-10-27 13:44
duplicate of https://github.com/emuflight/EmuConfigurator/issues/17

**Closed by gretel** 2019-10-27 13:44 UTC
